### ISSUE TITLE
install 后 node app.js 跑不起来哎。报错如下我不清楚什么错误。

### ISSUE THREAD

**Issue by xinghehaohan** [godghdai/spider#1]
/Users/su/Downloads/spider-master/Routers/default.js:15
    router.get('/listone', async (ctx,next) => {
                                 ^
SyntaxError: Unexpected token (
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:545:28)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/su/Downloads/spider-master/app.js:6:14)
    at Module._compile (module.js:573:32)

**Comment by godghdai** [comment]
估计你安装node版本有点低，不支持async

**Comment by godghdai** [comment]
估计你安装node版本有点低，不支持ES7的Async/Await
